### ISSUE TITLE
Drop erroneous claim that Ian is no longer editing HTML at WHATWG

### ISSUE THREAD

**Issue by hober** [w3c/spork#20]
Citation: https://html.spec.whatwg.org/multipage/acknowledgements.html#acknowledgments

Simplest change is to remove the (until August 2015) parenthetical. Maybe it got accidentally duplicated from Robin's line?

**Comment by stevefaulkner** [comment]
your wish is granted
https://github.com/w3c/spork/commit/44b7f37febb5e2a3007dd67289b5cb3067f8d714
